name: Local Microservice Development Dependencies
rating: 5
imageUrl: https://github.com/kibum0405/topping-wijmo/assets/59447401/f5a6193f-cce9-4f43-a8aa-23c269eabbd1
description: Local Microservice Development Dependencies including Kafka, Mockservers, API Gateway. 
tags:
  - Mock
  - Kafka
  - API
