name: Local Microservice Development Dependencies
rating: 5
imageUrl: https://github.com/kibum0405/topping-wijmo/assets/59447401/3cf4bb64-9128-4eae-8aba-7e70cb8b55fb
templateName: local-dep
description: Local Microservice Development Dependencies including Kafka, Mockservers, API Gateway.
depends:
tags:
  - Mock
  - Kafka
  - API
